fredrika/__init__.py
#! ../env/bin/python
# -*- coding: utf-8 -*-

from flask import Flask, request
from flask.ext.babel import Babel
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.debugtoolbar import DebugToolbarExtension
from flask.ext.login import LoginManager
from flask.ext.bcrypt import Bcrypt
from flask.ext.cache import Cache
from pyfcm import FCMNotification
import requests
import urllib
import os

# for parsing the content to text
import base64
from bs4 import BeautifulSoup
from lxml import html

# add logging
import logging
from logging.handlers import SysLogHandler

# time to config
app = Flask(__name__)
app.config.from_object(os.getenv('APP_SETTINGS', 'config.DevelopmentConfig'))

# setup logging handler
handler = SysLogHandler(address='/dev/log')
handler.setLevel(logging.INFO)
formatter = logging.Formatter( 'HesaFredrikaServer [%(process)d]: %(levelname)s: %(message)s')
handler.setFormatter(formatter)
app.logger.addHandler(handler)

# session captcha
# captcha anyone?
from flask_session import Session
from flask_session_captcha import FlaskSessionCaptcha
import uuid

Session(app)


from flask_mail import Mail
from flask_mail import Message
mail = Mail()
mail.init_app(app)

def send_to_email(topic, subject, message, location, message_id, raw, users):
    with mail.connect() as conn:
	for user in users:
            message = raw['info'][0]['description']
	    message = message + '\n\n' + u'URL: https://hesafredrika.se/message/%d' % message_id
	    subject = subject
	    msg = Message(recipients=[user.email],
			  body=message,
                          html=message,
			  subject=subject)

	    conn.send(msg)

def send_to_topic(topic, subject, message, location, message_id, raw):
    """Background task to send to firebase ip"""
    with app.app_context():
        result = {}
        push_service = FCMNotification(api_key=app.config['FIREBASE_API_KEY'])
        data_message = {
                'location' : location[0]['boundingbox'],
                'location_name' : location[0]['display_name'],
                'lat' : location[0]['lat'], 
                'lon' : location[0]['lon'] ,
                'place_id' : location[0]['place_id'],
                'message' : message,
                'message_id' : message_id,
                'message_subject' : subject,
                'topic_name' : topic,
                'description' : raw['info'][0]['description'],
            } 
        app.logger.info(data_message)

        result = push_service.notify_topic_subscribers(
                topic_name = "%d" % topic,
                data_message = data_message, 
                dry_run = app.config['FIREBASE_DRY_RUN'],
                content_available = True,
            )

        app.logger.info("firebase: %s" % result)

        if app.config['FIREBASE_DRY_RUN']:
            notify_admin('Sending message to hosts %s' % subject)

        # TODO: here we should have some potential error handling/logging
        # Just remember the call is ansyncronus, so we dont know when it returns
        if result['failure'] != 0:
            msg = "FCM did not succeed with send %s to %s, notifying admin " % (subject, topic)
            notify_admin(msg)

        return result['results']

def notify_admin(message):
    with app.app_context():
        url = 'https://api.pushbullet.com/v2/pushes'
        headers = {'Access-Token' : app.config['PUSHBULLET_API_KEY']}
        payload = {'type' : 'note',
                'title' : 'Hesa Fredrika',
                'body' : message }
        try:
            r = requests.post(url, headers=headers, json=payload)
        except:
            return False

        return r.json()

def locationfinder(location):
    ''' takes a list of location names and tries to find them in openstreetmap '''
    # base_url = 'http://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=se&'
    base_url = 'http://locationiq.org/v1/search.php?key=' + app.config['LOCATIONIQ_API_KEY'] + '&format=json&'
    with app.app_context():
        # probably only for tests:
        if 'hela landet' in location:
            location = 'Sverige'
       
        url = base_url + urllib.urlencode( {"q":location} )

        try:
            r = requests.get(url)
        except Exception as error:
            msg = 'error doing query to openstreetmap novatim: %s' % error
            notify_admin(msg)
            return False

        if r.json():
            return r.json()
        else:
            return False
        

def b64html2text(html):
    try:
        html = base64.b64decode(html)
    except:
        html = False

    if html:
        soup = BeautifulSoup(html, "html.parser")
        text = soup.text
    else:
        text = False

    return text

####################
#### extensions ####
####################

login_manager = LoginManager()
login_manager.init_app(app)
bcrypt = Bcrypt(app)
toolbar = DebugToolbarExtension(app)
cache = Cache(app)
db = SQLAlchemy(app)

captcha = FlaskSessionCaptcha(app)

babel = Babel(app)
@babel.localeselector
def get_locale():
    accept_languages = app.config.get('ACCEPT_LANGUAGES')
    return request.accept_languages.best_match(accept_languages)

###################
#### flask-login ####
####################

from models import User, Logging
login_manager.login_view = "main.login"
login_manager.login_message_category = "warning"

@login_manager.user_loader
def load_user(user_id):
        return User.query.filter(User.id == int(user_id)).first()

login_manager.init_app(app)

# register our blueprints
from fredrika.main.views import main
app.register_blueprint(main)

fredrika/main/views.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, flash, request, redirect, url_for, g, Flask, Response, jsonify
from flask.ext.login import login_user, logout_user, login_required, current_user
from sqlalchemy.orm import load_only

from fredrika.forms import LoginForm, MessageForm, UserForm, TopicForm, MessageEditForm, VolunteerForm, SignupForm
from fredrika.models import User, Org, Municipality, Topic, Logging, Volunteer, Message, Signup
from fredrika import db, locationfinder, notify_admin, send_to_topic, send_to_email, b64html2text, captcha
from flask.ext.babel import gettext
import requests
import json
import base64
import datetime
import time

main = Blueprint('main', __name__)

@main.route('/', methods=["GET", "POST"])
#@cache.cached(timeout=1000)
def home():
    if current_user.is_authenticated():
        return redirect(url_for('.dashboard'))

    form = SignupForm()

    if form.validate_on_submit():
        if captcha.validate():
            pass
        else:
            flash( gettext(u'Felaktig Captcha'), 'error')
            return redirect(url_for('.home'))

        # time to validate email
        email = Signup.query.filter(Signup.email==form.email.data).first()
        if not email:
            signup = Signup()
            form.populate_obj(signup)
            db.session.add(signup)
            db.session.commit()
            flash( gettext(u'Din e-mail finns nu på VMA-utskickslistan: ') + signup.email, 'success')
            return redirect(url_for('.home'))
        else:
            flash( gettext(u'Din e-mail finns redan i VMA-utskickslistan! '), 'error')
            return redirect(url_for('.home'))

    return render_template('index.html', form=form)

#    return render_template('index.html')

@main.route('/om')
def about():

    return render_template('about.html')

@main.route('/send', methods=["GET", "POST"])
@login_required
def send():
    form = MessageForm()

    topics = []
    td = Topic.query.filter(Topic.org_id==current_user.org_id).order_by(Topic.name).all()
    for t in td:
        topics.append((t.id, t.name))

    form.topic_id.choices = topics

    if form.validate_on_submit():
        #for the loop to work
        org_id=current_user.org_id
        user_id=current_user.id

        # send mesg, iterate through form.topic.data
        sent = []

        # these two are not used for manual sends
        location = False # feel free to extend with osm location data
        source_id = "manual" 

        topic = int(form.topic_id.data)
        sent.append(topic)
        message = form.message.data.encode('utf-8').strip()
        location = form.location.data.encode('utf-8').strip()

        raw = {}
        raw['identifier'] = datetime.datetime.utcfromtimestamp(time.time()).strftime('HF-%Y%m%d-%H%M%S-Z')
        raw['info'] = [{ 'description' : form.description.data } ]

        msg = Message()
        msg.subject = form.subject.data
        msg.message = base64.b64encode(message)
        msg.active = True
        msg.raw = raw
        msg.topic_id = topic
        msg.location = locationfinder(location)
        if not msg.location:
            form.location.errors.append(gettext('Location could not be found'))
            return render_template('dashboard.html', form=form)

        db.session.add(msg)
        db.session.commit()

        # TODO: Refactor this to use Message table instead

        # we do this to clean the form by reloading the page
        flash(gettext('Your message was sent added to the send queue'),'success')
        return redirect(url_for('.dashboard'))

    return render_template('dashboard.html', form=form)

@main.route('/topics', methods=['GET', 'POST'])
@login_required
def topics():
    topics = Topic.query.order_by(Topic.name).all()
    form = TopicForm()
    if form.validate_on_submit():
        topic = Topic.query.filter(Topic.name==form.name.data).first()
        if not topic:
            topic = Topic()
            form.populate_obj(topic)
            db.session.add(topic)
            db.session.commit()
            flash(u'Topic %s added.' % form.name.data )
            return redirect(url_for('.topics'))
        else:
            form.name.errors.append(u'Topic already exists')

    return render_template('topics.html', data=topics, form=form)

@main.route('/topic/edit/<int:topic>', methods=['GET', 'POST'])
@login_required
def topic_edit(topic=False):
    topic = Topic.query.filter(Topic.id==topic).first()
    form = TopicForm(obj=topic)
    if form.validate_on_submit():
        form.populate_obj(topic)
        db.session.add(topic)
        db.session.commit()
        flash(u'Topic %s edited.' % topic.name )
        return redirect(url_for('.topics'))

    return render_template('topics.html', data=False, form=form)

@main.route('/dashboard', methods=['GET', 'POST'])
@main.route('/dashboard/<int:page>', methods=['GET', 'POST'])
@login_required
def dashboard(page=1):

    # handle toggle of active to inactive
    inactive = request.args.get("inactivate")
    if inactive:
        msg = Message.query.filter_by(id=int(inactive)).first()
        msg.active = False
        db.session.add(msg)
        db.session.commit()
        return redirect(url_for('.dashboard'))

    active = request.args.get("activate")
    if active:
        msg = Message.query.filter_by(id=int(active)).first()
        msg.active = True
        db.session.add(msg)
        db.session.commit()
        return redirect(url_for('.dashboard'))

    # post per page for pagination
    ppp = 50
    query = Message.query.filter(Message.org_id==current_user.org_id).order_by(db.desc(Message.created)).paginate(page, ppp, False)
    return render_template('logging.html', data=query)

@main.route('/users', methods=['GET', 'POST'])
@login_required
def users():
    users = User.query.filter(User.org_id==current_user.org_id).order_by(User.created).all()
    form = UserForm()
    if form.validate_on_submit():
        user = User.query.filter(User.email == form.data['email']).first()
        if user:
            form.email.errors.append(u'Topic already exists')
        else:
            user = User(email=form.data['email'],
                           name=form.data['name'],
                           password=form.data['password'],
                           org_id = current_user.org_id,
                           )
            user.admin = True
            db.session.add(user)
            db.session.commit()
            flash(u'User created')
            return redirect(url_for('.users'))

    return render_template('users.html', form=form, data=users)

@main.route('/users/edit/<int:edit>', methods=['GET', 'POST'])
def user_edit(edit=0):
    user = User.query.filter(User.id==edit, User.org_id==current_user.org_id).first()

    form = UserForm(obj=user)

    if form.validate_on_submit():
        user.name = form.data['name']
        user.email= form.data['email']
        if form.data['password']:
            user.set_password(form.data['password'])

        db.session.commit()
        
        flash('User updated')
        return redirect(url_for('.users'))
    
    return render_template('users.html', form=form, data=False)

@main.route('/users/delete/<int:delete>', methods=['GET', 'POST'])
def user_delete(delete=0):
    user = User.query.filter(User.id==delete, User.org_id==current_user.org_id).delete()
    db.session.commit()
    flash(u'User deleted')
    return redirect(url_for('.users'))

@main.route('/signups')
@login_required
def signups():
    delete = request.args.get('delete')
    if delete:
        Signup.query.filter_by(id=int(delete)).delete()
        db.session.commit()
        flash(gettext("Deleted email ") +  str(delete), "success")
        return redirect(url_for(".signups"))

    users = Signup.query.order_by(Signup.created).all()
    return render_template('signups.html', data=users)


''' Volunteer stuff '''
@main.route('/volunteer', methods=['GET', 'POST'])
@login_required
def volunteer():
    volunteers = Volunteer.query.order_by(Volunteer.name).all()
    form = VolunteerForm()
    if form.validate_on_submit():
        volunteer = Volunteer.query.filter(Volunteer.name==form.name.data).first()
        if not volunteer:
            volunteer = Volunteer()
            form.populate_obj(volunteer)
            db.session.add(volunteer)
            db.session.commit()
            flash(u'Volunteer topic%s added.' % form.name.data )
            return redirect(url_for('.volunteer'))
        else:
            form.name.errors.append(u'Volunteer topic already exists')

    return render_template('volunteers.html', data=volunteers, form=form)

@main.route('/volunteer/edit/<int:topic>', methods=['GET', 'POST'])
@login_required
def volunteer_edit(volunteer=False):
    volunteer = Volunteer.query.filter(Volunteer.id==volunteer).first()
    form = TopicForm(obj=volunteer)
    if form.validate_on_submit():
        form.populate_obj(volunteer)
        db.session.add(volunteer)
        db.session.commit()
        flash(u'Volunteer topic %s edited.' % volunteer.name )
        return redirect(url_for('.volunteer'))

    return render_template('volunteers.html', data=False, form=form)

''' End volunteer stuff '''

@main.route('/admin/org', methods=['GET', 'POST'])
@login_required
def admin_org(page=1):
    log = Org.query.all()

    return render_template('logging.html', data=log)

@main.route("/message/edit/<int:mid>", methods=['GET', 'POST'])
@login_required
def message_edit(mid=0):
    delete = request.args.get('delete')
    if delete:
        Message.query.filter_by(id=mid).delete()
        db.session.commit()
        flash(gettext("Deleted Message ") + str(mid), "success")
        return redirect(url_for('.dashboard'))

    message = Message.query.filter_by(id=mid).first()
    form = MessageEditForm(obj=message)
    if form.validate_on_submit():
        form.populate_obj(message)
        # Override the auto form to handle utf-8 and b64encode

fredrika/templates/about.html
{% extends "base.html" %}

{% block title %}Hem{% endblock %}

{% block body %}

    <div class="row">
	    <div class="hidden-xs col-sm-7 col-md-6 col-lg-5" style="margin-top: -50px; margin-bottom: -60px;">
		    <img class="img-responsive" src="{{url_for('static', filename='images/horn.png')}}">
	    </div>
	    <div class="visible-xs col-xs-8 col-xs-offset-2" style="margin-top: -50px;">
		    <img class="img-responsive" src="{{url_for('static', filename='images/horn-mob.png')}}">
	    </div>
        <div class="col-xs-12 col-sm-6 col-md-5 col-lg-5 col-lg-offset-1">
			<br>
			<h1>Om Hesa Fredrika</h1>
			
			<h3>Viktigt Meddelande till Allmänheten via App</h3>
			<br><br>		
			<p>Idag får en stor majoritet av befolkningen stora mängder av notifikationer i fickan. Varför ska då dessa få potentiellt livsviktiga meddelanden enbart distribueras genom en ljudsignal, följt av meddelande via lokalradio?</p>

			<p>Vi vill med detta projekt visa hur enkelt det är att göra just detta, samt visa på möjligheterna som ett digitalt distributionssystem kan tillföra.</p>
			<p>Ljudsignalen, i folkmun kallad Hesa Fredrik, som används för VMA har fått ge namn till Hesa Fredrika.</p>
			
			<p>Vill du få kontakt med oss gör du det enklast via "tut at hesafredrika punkt se".</p>
			
			<h3>Teknik</h3>
			<p>Appen använder push-notifieringar för att skicka ut alarm. Ingen användarinformation sparas på våra servrar utan appen kollar om enheten är i det område som push-notifieringen täcker, eller om något av de områden som man själv har lagt till i appen matchar alarmets område.</p>
			<p>Om du valt att ange din epostadress, kommer vi enbart att maila ut VMA, och inget annat.</p>
			
			<h3>Finansiering och källkod</h3>
			<p><b>Detta projekt har gjorts möjligt genom finansiering av <a href="https://www.iis.se" target="_blank">Internetfonden IIS</a> (Internetstiftelsen i Sverige).</b></p>
			<br>
			<p><b>Hesa Fredrika är öppen källkod (Open Source) och du kan hitta hela projektet här: <a href="https://gitlab.com/hesafredrika" target="_blank">gitlab.com/hesafredrika</a>.</b></p>
			<br>
			<a href="/">&laquo; {{ gettext('Tillbaka') }}</a>
			<h3>Datalagring</h3>
        </div>
    </div>

{% endblock %}

fredrika/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
		<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
		<meta name="flattr:id" content="14zd8j">

        {% block css %}
        {% endblock %}

	{% if current_user.is_authenticated() %}
		<script data-require="jquery@*" data-semver="2.0.3" src="https://code.jquery.com/jquery-2.0.3.min.js"></script>
    	<script data-require="bootstrap@*" data-semver="3.1.1" src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
	{% endif %}
		<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
	    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet">
   		<link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.3.2/css/simple-line-icons.css" rel='stylesheet' type='text/css'>
		<link href="{{url_for('static', filename='css/hesafredrika.css')}}" rel="stylesheet" media="screen">
		  
		{#

		{% if current_user.is_authenticated() %}
		  {% if current_user.is_admin() == 'True' %}
			<link href="{{url_for('static', filename='css/admin.css')}}" rel="stylesheet" media="screen">
			<link href="{{url_for('static', filename='css/jquery.embed.min.css')}}" rel="stylesheet" media="screen">
		  {% endif %}
		{% endif %}

		#}

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

	</head>

    <body>

{% if current_user.is_authenticated() %}
  {% include 'header.html' %}
{% endif %}

        <div class="container">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }} alert-dismissible" role="alert">
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                          {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {% block body %}
            {% endblock %}

        </div>
        
        {% block js %}
        {% endblock %}

		<!-- child template -->
		{% block content %}{% endblock %}
		
    {% include 'foot.html' %}

		
    </body>
</html>

fredrika/templates/dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-lg-12">
			<div class="col-xs-offset-1">
				{{ gettext ("To send a message, enter your text and select the topic, then press send.") }}
			</div>
        </div>
    </div>
	<div>

	</div>

    <div class="row">
            <form role="form" action="" method="post">
                {{ form.hidden_tag() }}

            <div class="form-group", style="width: 25%">
                {{ form.topic_id.label }}
                {{ form.topic_id(class_="form-control") }}
                {% if form.topic_id.errors %}
                    {% for e in form.topic_id.errors %}
                        <p class="help-block">{{ e }}</p>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="form-group" style="width: 50%">
                {{ form.subject.label }}
                {{ form.subject(class_="form-control", value="VMA - Viktigt meddelande till allmänheten") }}
                {% if form.subject.errors %}
                    {% for e in form.subject.errors %}
                        <p class="help-block">{{ e }}</p>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="form-group", style="width: 50%">
                {{ form.location.label }}
				{{ form.location(class_="form-control", value="Torshavn Faroe Islands", size=10) }}
                {% if form.location.errors %}
                    {% for e in form.location.errors %}
                        <p class="help-block">{{ e }}</p>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="form-group" style="width: 50%">
                {{ form.description.label }}
                {{ form.description(class_="form-control", value="Kort beskrivning utan HTML") }}
                {% if form.description.errors %}
                    {% for e in form.description.errors %}
                        <p class="help-block">{{ e }}</p>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="form-group" style="width: 50%">
                {{ form.message.label }}
                {{ form.message(class_="form-control", cols="25", rows="10") }}
                {% if form.message.errors %}
                    {% for e in form.message.errors %}
                        <p class="help-block">{{ e }}</p>
                    {% endfor %}
                {% endif %}
            </div>
		
    </div> {# end row #}
	<button type="submit" class="btn btn-primary">{{ gettext("Send") }}</button>
        </form>

{% endblock %}

fredrika/templates/foot.html
<div class="foot col-sm-12 text-center">
	<a href="/om">Om Hesa Fredrika</a>
</div>

fredrika/templates/header.html
<!-- Navigation -->

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-menu"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse">
     <div class="navbar-left">
        <ul class="nav navbar-nav">
        {% if current_user.is_authenticated() %}
         	{% if current_user.admin %}
			<li><a href="{{ url_for('.send') }}"><span class="icon-feed"></span> {{ _("Send") }} </a></li>
			{% endif %}
		{% endif %}
        </ul>
     </div>
     <div class="navbar-right">
        <ul class="nav navbar-nav">
         {% if current_user.is_authenticated() %}
         	{% if current_user.admin %}
			<li><a href="{{ url_for('.dashboard') }}"><span class="icon-list"></span> {{ _("Logs") }} </a></li>
			<li><a href="{{ url_for('.topics') }}"><span class="icon-list"></span> {{ _("Topics") }} </a></li>
			{# <li><a href="{{ url_for('.volunteer') }}"><span class="icon-list"></span> {{ _("Volunteers") }} </a></li> #}
			<li><a href="{{ url_for('.signups') }}"><span class="icon-people"></span> {{ _("Subs") }} </a></li>
			{% endif %}
			<li><a href="{{ url_for('.users') }}"><span class="icon-people"></span> {{ _("Users") }} </a></li>
				{% if current_user.name %}
					<p class="navbar-text"><span class="icon-user"></span> {{current_user.name}}</p>
				{% else %}
					<p class="navbar-text"><span class="icon-user"></span> {{current_user.email}}</p>
				{% endif %}
				<li><a href="{{ url_for('.logout') }}"><span class="icon-logout"></span> {{ _("Sign out") }} </a></li>
          {% else %}
		  <li><a href="{{ url_for('.login') }}"><span class="icon-login"></span> {{ _("Sign in") }} </a></li>
	  	  {% endif %}
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </div>
</nav>

fredrika/templates/logging.html
{% extends "base.html" %}

{% block title %}Message log{% endblock %}

{% block body %}

	<div class="container-fluid">
		<div class="row" style="background-color: #ccc;">
			<div class="col-sm-2" align=center>
				Date - Time	
			</div>
			<div class="col-sm-1">
				Topic
			</div>
			<div class="col-sm-1" align=center>
				Active
			</div>
			<div class="col-sm-1" align=center>
				Error
			</div>
			<div class="col-sm-3">
				Location
			</div>
			<div class="col-sm-1">
				URL	
			</div>
			<div class="col-sm-1">
				Delivered
			</div>
			<div class="col-sm-2" align="center">
				Identifier
			</div>
			{#
			<div class="col-sm-1" align=center>
				Sender
			</div>
			#}
		</div>
		{% for l in data.items %}
			<div class="row" style="background-color: #{{ loop.cycle('eee', 'ddd') }};">
				<div class="col-sm-2">
					{{ l.created.strftime('%Y-%m-%d  %H:%M:%S') }}
				</div>
				<div class="col-sm-1">
					{{ l.topic.name }}
				</div>
				<div class="col-sm-1" align=center>
					{% if l.active %}
						<a href="{{ url_for('.dashboard', inactivate=l.id ) }} "> <span class="icon-check"></a>
					{% else %}
						<a href="{{ url_for('.dashboard', activate=l.id ) }} "> <span class="icon-plus"></a>
					{%endif%}
				</div>
				<div class="col-sm-1" align=center>
					{% if l.error %}
					{{ l.error }}
					{% endif %}
				</div>
				<div class="col-sm-3">
					{% if l.location[0] %}
					{{ l.location[0]['display_name'] }}
					{% else %}
					{{ l.location }}
					{% endif %}
				</div>
				<div class="col-sm-1">
					<a href="{{ url_for('main.message_public', mid=l.id ) }} ">link</a>
				</div>
				<div class="col-sm-1" align=center>
					{% if l.delivered %} <span class="icon-check"> {%endif%}
				</div>
				<div class="col-sm-2" align=center>
					<a href="{{ url_for('main.message_edit', mid=l.id ) }} ">{% if l.raw.identifier %} {{ l.raw.identifier }} {%endif%}</a>
				</div>
				{#
				<div class="col-sm-1" align=center>
					{% if l.user.name %} {{ l.user.name }} {%else%} {{ l.user.email }} {%endif%}
				</div>
				#}
			</div>
		{% endfor %}	
	</div> {# end container table #}

		{# pagination #}
      <div>
      {% if data.has_prev %}<a href="{{ data.prev_num }}">&lt;&lt; Previous page</a> | {% endif %}
          {% for page in data.iter_pages(left_edge=2, left_current=2, right_current=2, right_edge=2) %}
            {% if page %}
              {% if page != data.page %}
                <a href="{{ url_for('main.dashboard', page=page) }}">{{ page }}</a>
              {% else %}
                <strong>{{ page }}</strong>
              {% endif %}
            {% endif %}
          {% endfor %}
       {% if data.has_next %}
        | <a href="{{ url_for('main.dashboard', page=data.next_num) }}">Next page &gt;&gt;</a>
        {% endif %}
          </div>
        <div>
          <br>
          {% if data.has_next %}
            page: {{ data.page }} of {{ data.pages }}
          {% endif %}
        </div>



{% endblock %}

fredrika/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
    <h1 class="text-center">Fredrika Login</h1>

    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <form role="form" action="{{ url_for('.login') }}" method="post">
                {{ form.hidden_tag() }}

                <div class="form-group">
                    {{ form.email.label }}
                    {% if form.email.errors %}
                        {% for e in form.email.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.email(class_="form-control") }}
                </div>
                <div class="form-group">
                    {{ form.password.label }}
                    {% if form.password.errors %}
                        {% for e in form.password.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.password(class_="form-control") }}
                </div>

                <button type="submit" class="btn btn-primary">Login</button>
            </form>
        </div>
        <div class="col-md-4"></div>
    </div>

{% endblock %} {# end of content block #}